# Generated by Django 5.2.17 on 2026-10-03 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=15)),
                ('idempotency_key', models.UUIDField(help_text='Ensures idempotent requests', unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'status', 'is_deleted'], name='bookings_bo_event_i_bded0a_idx'), models.Index(fields=['user', 'status', 'is_deleted'], name='bookings_bo_user_id_4f5276_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['PENDING', 'CONFIRMED'])), fields=('user', 'event'), name='unique_active_booking_per_user')],
            },
        ),
    ]
